server:
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  grpc_client:
    target: dns:///127.0.0.1:9000
observability:
  global_attributes:
    service.group: template
    region: local
  tracing:
    enabled: true
    exporter: stdout
    sampling_ratio: 1.0
    required: false
  metrics:
    enabled: true
    exporter: stdout
    interval: 60s
    disable_runtime_stats: false
    required: false
    grpc_enabled: true
    grpc_include_health: false
