server:
  grpc:
    addr: 0.0.0.0:9102
    timeout: 5s
data:
  postgres:
    dsn: "" # 环境变量 DATABASE_URL 覆盖此值
    max_open_conns: 10
    min_open_conns: 2
    max_conn_lifetime: 3600s
    max_conn_idle_time: 1800s
    health_check_period: 60s
    schema: catalog
    enable_prepared_statements: false
  grpc_client:
    target: 127.0.0.1:9101
